# -*- coding: utf-8 -*-
"""CSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYviteL-1JOhwBcljxIaOsWLoEisXG0o
"""

import os
import json
from ortools.sat.python import cp_model

class PackingCSP:


    def __init__(self, caixas, L, W, H, verbose=True):
        self.caixas = caixas
        self.L = L
        self.W = W
        self.H = H
        self.verbose = verbose

        self.pasta_resultados = "resultados_csp"
        os.makedirs(self.pasta_resultados, exist_ok=True)

        # Inicializa o modelo matemático do CSP
        self.model = cp_model.CpModel()

    def get_dimensoes_efetivas_csp(self, caixa, r_var):
        """Retorna as dimensões efetivas (l, w, h) baseadas na variável de rotação do CSP"""
        _, l, w, h, _, _ = caixa

        l_ef = self.model.NewIntVar(0, max(l, w), "")
        w_ef = self.model.NewIntVar(0, max(l, w), "")

        # Rotação idêntica: r=0 -> (l,w,h) | r=1 -> (w,l,h)
        self.model.Add(l_ef == l).OnlyEnforceIf(r_var.Not())
        self.model.Add(w_ef == w).OnlyEnforceIf(r_var.Not())

        self.model.Add(l_ef == w).OnlyEnforceIf(r_var)
        self.model.Add(w_ef == l).OnlyEnforceIf(r_var)

        return l_ef, w_ef, h

    def executar(self):
        if self.verbose:
            print("="*50)
            print("EXECUTANDO CSP COM LÓGICA ESPELHADA (BRKGA)")
            print("="*50)

        n = len(self.caixas)

        # 1. DECLARAÇÃO DE VARIÁVEIS
        x = []
        y = []
        z = []
        r = []
        l_ef_vars = []
        w_ef_vars = []

        for i, caixa in enumerate(self.caixas):
            _, l, w, h, _, _ = caixa

            # Variáveis de decisão do Solver
            r_var = self.model.NewBoolVar(f'r_{i}')

            # Substitui os cálculos de max_x, max_y, max_z do seu decoder
            l_ef, w_ef, h_ef = self.get_dimensoes_efetivas_csp(caixa, r_var)

            x_var = self.model.NewIntVar(0, self.L, f'x_{i}')
            y_var = self.model.NewIntVar(0, self.W, f'y_{i}')
            z_var = self.model.NewIntVar(0, self.H, f'z_{i}')

            # Garante estritamente os limites físicos do container (min/max do seu decoder)
            self.model.Add(x_var + l_ef <= self.L)
            self.model.Add(y_var + w_ef <= self.W)
            self.model.Add(z_var + h_ef <= self.H)

            x.append(x_var)
            y.append(y_var)
            z.append(z_var)
            r.append(r_var)
            l_ef_vars.append(l_ef)
            w_ef_vars.append(w_ef)

        # 2. RESTRIÇÕES ESPELHADAS DO SEU CÓDIGO ORIGINAL

        # Restrição 1: verifica_todas_sobreposicoes
        for i in range(n):
            for j in range(i + 1, n):
                # Variáveis auxiliares para verificar colisão em cada eixo
                x_over = self.model.NewBoolVar('')
                y_over = self.model.NewBoolVar('')
                z_over = self.model.NewBoolVar('')

                # Lógica: (x1 < x2 + l2 e x1 + l1 > x2)
                self.model.Add(x[i] < x[j] + l_ef_vars[j]).OnlyEnforceIf(x_over)
                self.model.Add(x[i] + l_ef_vars[i] > x[j]).OnlyEnforceIf(x_over)

                self.model.Add(y[i] < y[j] + w_ef_vars[j]).OnlyEnforceIf(y_over)
                self.model.Add(y[i] + w_ef_vars[i] > y[j]).OnlyEnforceIf(y_over)

                self.model.Add(z[i] < z[j] + self.caixas[j][3]).OnlyEnforceIf(z_over)
                self.model.Add(z[i] + self.caixas[i][3] > z[j]).OnlyEnforceIf(z_over)

                # No BRKGA, se os 3 eixos sobrepõem, havia penalidade. No CSP isso é proibido:
                sobrepõe = self.model.NewBoolVar('')
                self.model.AddBoolAnd([x_over, y_over, z_over]).OnlyEnforceIf(sobrepõe)
                self.model.Add(sobrepõe == 0) # Força a NÃO haver sobreposição

        #Restrição 2: verifica_estabilidade_geral
        for i in range(n):
            _, l_orig, w_orig, _, _, _ = self.caixas[i]

            # Como o CSP precisa saber o tamanho máximo do laço antes de rodar,
            # iteramos sobre o maior espaço possível (max de l ou w) e filtramos estritamente
            for dx in range(max(l_orig, w_orig)):
                for dy in range(max(l_orig, w_orig)):

                    # Condição: o ponto dx, dy só existe se estiver dentro da dimensão efetiva atual
                    ponto_valido = self.model.NewBoolVar('')
                    self.model.Add(dx < l_ef_vars[i]).OnlyEnforceIf(ponto_valido)
                    self.model.Add(dy < w_ef_vars[i]).OnlyEnforceIf(ponto_valido)

                    # Se o ponto é válido e z > 0, ele precisa de suporte (Exatamente seu laço original)
                    ponto_suportado = self.model.NewBoolVar('')

                    # Verifica se o chão apoia diretamente
                    self.model.Add(z[i] == 0).OnlyEnforceIf(ponto_suportado)

                    opcoes_suporte = []
                    for j in range(n):
                        if i == j: continue

                        ponto_em_j = self.model.NewBoolVar('')
                        # xo <= x + dx < xo + lo_ef
                        self.model.Add(x[j] <= x[i] + dx).OnlyEnforceIf(ponto_em_j)
                        self.model.Add(x[i] + dx < x[j] + l_ef_vars[j]).OnlyEnforceIf(ponto_em_j)
                        # yo <= y + dy < yo + wo_ef
                        self.model.Add(y[j] <= y[i] + dy).OnlyEnforceIf(ponto_em_j)
                        self.model.Add(y[i] + dy < y[j] + w_ef_vars[j]).OnlyEnforceIf(ponto_em_j)
                        # zo + ho_ef == z
                        self.model.Add(z[j] + self.caixas[j][3] == z[i]).OnlyEnforceIf(ponto_em_j)

                        opcoes_suporte.append(ponto_em_j)

                    # O ponto está suportado se o chão apoia OU se alguma caixa j apoia
                    self.model.AddBoolOr(opcoes_suporte).OnlyEnforceIf(ponto_suportado)

                    # Se o ponto for válido, ele OBRIGATORIAMENTE tem que estar suportado
                    self.model.Add(ponto_suportado == 1).OnlyEnforceIf(ponto_valido)

        #Restrição 3: verifica_ordem_entrega
        for i in range(n):
            for j in range(i + 1, n):
                d_i = self.caixas[i][4]
                d_j = self.caixas[j][4]

                # Espelhando exatamente sua função 'verifica_ordem_entrega':

                if d_i < d_j:
                    self.model.Add(x[i] <= x[j])
                elif d_j < d_i:
                    self.model.Add(x[j] <= x[i])

        # 3. EXECUÇÃO DO SOLVER
        solver = cp_model.CpSolver()
        solver.parameters.max_time_in_seconds = 60.0  # Limite de tempo ajustável

        status = solver.Solve(self.model)

        # 4. FORMATAÇÃO DE SAÍDA IGUAL AO SEU SCRIPT
        if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
            melhor_solucao = []
            volume_ocupado = 0

            for i in range(n):
                res_x = solver.Value(x[i])
                res_y = solver.Value(y[i])
                res_z = solver.Value(z[i])
                res_r = solver.Value(r[i])
                melhor_solucao.append((res_x, res_y, res_z, res_r))

                _, l, w, h, _, _ = self.caixas[i]
                l_ef = w if res_r == 1 else l
                w_ef = l if res_r == 1 else w
                volume_ocupado += l_ef * w_ef * h

            volume_total = self.L * self.W * self.H
            utilizacao = volume_ocupado / volume_total


            dados = {
                'melhor_fitness': utilizacao,
                'melhor_solucao': melhor_solucao,
                'historico': [utilizacao],
                'volume_total': volume_total,
                'volume_ocupado': volume_ocupado,
                'utilizacao': utilizacao,
                'L': self.L, 'W': self.W, 'H': self.H,
                'caixas': [{'id': c[0], 'l': c[1], 'w': c[2], 'h': c[3], 'prioridade': c[4], 'nome': c[5]} for c in self.caixas]
            }

            with open(f"{self.pasta_resultados}/resultados.json", "w", encoding="utf-8") as f:
                json.dump(dados, f, indent=2)

            return melhor_solucao, utilizacao, [utilizacao]
        else:
            print("❌ Nenhuma solução factível encontrada com essas restrições.")
            return None, 0, []

# Bloco de execução
if __name__ == "__main__":
    L, W, H = 10, 8, 6
    caixas = [
        (1, 3, 2, 2, 0, "A"),
        (2, 2, 2, 3, 0, "B"),
        (3, 4, 2, 1, 1, "C"),
        (4, 2, 2, 2, 1, "D"),
        (5, 3, 2, 2, 1, "E"),
        (6, 5, 2, 1, 2, "F"),
        (7, 4, 3, 1, 2, "G"),
    ]

    csp = PackingCSP(caixas=caixas, L=L, W=W, H=H, verbose=True)
    solucao, fitness, hist = csp.executar()